// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./../globals/layouts/admin/Admin.vue')['default']
    Defaut: typeof import('./../globals/layouts/default/Defaut.vue')['default']
    LoginForm: typeof import('./../modules/authentication/components/forms/LoginForm.vue')['default']
    LoginPage: typeof import('./../modules/authentication/pages/LoginPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
